/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrackTruckRouteImport } from './routes/_app/track-truck'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppDriverRouteImport } from './routes/_app/driver'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppComplaintsRouteImport } from './routes/_app/complaints'
import { Route as AppCollectorRouteImport } from './routes/_app/collector'
import { Route as AppCollectionsRouteImport } from './routes/_app/collections'
import { Route as AppAwardsRouteImport } from './routes/_app/awards'
import { Route as AppAdminRouteImport } from './routes/_app/admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackTruckRoute = AppTrackTruckRouteImport.update({
  id: '/track-truck',
  path: '/track-truck',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverRoute = AppDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsRoute = AppComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectorRoute = AppCollectorRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppAwardsRoute = AppAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/awards': typeof AppAwardsRoute
  '/collections': typeof AppCollectionsRoute
  '/collector': typeof AppCollectorRoute
  '/complaints': typeof AppComplaintsRoute
  '/dashboard': typeof AppDashboardRoute
  '/driver': typeof AppDriverRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/track-truck': typeof AppTrackTruckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/awards': typeof AppAwardsRoute
  '/collections': typeof AppCollectionsRoute
  '/collector': typeof AppCollectorRoute
  '/complaints': typeof AppComplaintsRoute
  '/dashboard': typeof AppDashboardRoute
  '/driver': typeof AppDriverRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/track-truck': typeof AppTrackTruckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/awards': typeof AppAwardsRoute
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/collector': typeof AppCollectorRoute
  '/_app/complaints': typeof AppComplaintsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/driver': typeof AppDriverRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/track-truck': typeof AppTrackTruckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/awards'
    | '/collections'
    | '/collector'
    | '/complaints'
    | '/dashboard'
    | '/driver'
    | '/notifications'
    | '/settings'
    | '/track-truck'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/awards'
    | '/collections'
    | '/collector'
    | '/complaints'
    | '/dashboard'
    | '/driver'
    | '/notifications'
    | '/settings'
    | '/track-truck'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/awards'
    | '/_app/collections'
    | '/_app/collector'
    | '/_app/complaints'
    | '/_app/dashboard'
    | '/_app/driver'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/track-truck'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/track-truck': {
      id: '/_app/track-truck'
      path: '/track-truck'
      fullPath: '/track-truck'
      preLoaderRoute: typeof AppTrackTruckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/driver': {
      id: '/_app/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AppDriverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints': {
      id: '/_app/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AppComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collector': {
      id: '/_app/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof AppCollectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/awards': {
      id: '/_app/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AppAwardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAwardsRoute: typeof AppAwardsRoute
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppCollectorRoute: typeof AppCollectorRoute
  AppComplaintsRoute: typeof AppComplaintsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDriverRoute: typeof AppDriverRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrackTruckRoute: typeof AppTrackTruckRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAwardsRoute: AppAwardsRoute,
  AppCollectionsRoute: AppCollectionsRoute,
  AppCollectorRoute: AppCollectorRoute,
  AppComplaintsRoute: AppComplaintsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDriverRoute: AppDriverRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrackTruckRoute: AppTrackTruckRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
